export interface ICharacterHistory {
  history: string
}

export interface SkillAbility {
  skillName: string
  commandSkill: string
  url: string
}

export interface CharacterInfo {
  id: number
  ment: string
  name: string
  job: string
  charactermessage: string
  realName: string
  age: string
  homeWorld: string
  tacticalAbliity: string
  passiveAbility: string
  ultimateAbility: string
  character_select_url: string
  character_example_url: string
  ambition: string
  weapon_url: string
  character_history: ICharacterHistory[]
  skillAbility: SkillAbility[]
}

export const Request_CharacterInfo: CharacterInfo[] = [
  {
    id: 1,
    ment: `“All life is precious"`,
    name: 'OLIE',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
    character_select_url: '/characters/OLIE.png',
    character_example_url: '/guide/character/OLIE.png',
    character_history: [
      {
        history: '',
      },
      {
        history: '',
      },
      {
        history: '',
      },
    ],
    weapon_url: '/characters/OLIE/weapon.png',
    ambition: `Idol Cindy! A job called an idol that was no longer needed in the Apocalypse era after the sinkhole incident, but she still claims to be an idol. Having gained psychotic and abnormal physical abilities through her work at the mining site,Once again, I'll use this power to make my debut as an idol on the battlefield idol!`,
    skillAbility: [
      {
        skillName: 'one',
        commandSkill: 'weapon skill',
        url: '/characters/MICHELLE/skill_one.png',
      },
      {
        skillName: 'two',
        commandSkill: 'E skill',
        url: '/characters/MICHELLE/skill_two.png',
      },
      {
        skillName: 'three',
        commandSkill: 'shift skill',
        url: '/characters/MICHELLE/skill_three.png',
      },
    ],
  },
  {
    id: 2,
    ment: `"Hello~\nI'm your idol, Cindy."`,
    name: 'CINDY',
    job: 'delivery',
    charactermessage: `"Hello~\nI'm your idol, Cindy."`,
    ambition: `Idol Cindy! A job called an idol that was no longer needed in the Apocalypse era after the sinkhole incident, but she still claims to be an idol. Having gained psychotic and abnormal physical abilities through her work at the mining site,Once again, I'll use this power to make my debut as an idol on the battlefield idol!`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
    character_select_url: '/characters/CINDY.png',
    character_example_url: '/guide/character/CINDY.png',
    character_history: [
      {
        history: `Cindy succeeded in debuting as an idol after a long training period. Although he did not make it to the big list as a rookie, he was gradually gaining popularity. However, she, who was hurt by the stress of her life in the entertainment industry and separated herself from her character in public, sometimes showed a tendency to be violent and not know where to go when people were away. At some point Dyson Spear is about to be completed. Invited as a guest singer for Dyson Spear's completion ceremony, she was getting ready to take the stage.`,
      },
      {
        history: `The sinkhole incident at that point. Everything was sucked underground, and she survived the whole thing. However, the job and status of an idol singer was not important to her immediate survival in the devastated Apocalypse world, so no one offered or protected her. She enters a shelter to survive and volunteers for gem mining. Soon after, she was put into the work of combining Gem with Halo with Gem Mining, and as a side effect, a violent personality was noticeable in her.`,
      },
      {
        history: `Since then, the prisoners have begun to occupy most of the miners, and her violence has increased further, and using the superhuman power generated by the side effects, she escapes from the mining site and lives in the rubble of the collapsed building.One day, "X" appeared in front of her, who lived in violence looting the mining site and surroundings. Although she was an unknown person, I recommend you to join the organization you are creating because you will provide her with a constant battleground. She is curious about such "X" and accompanies him, but draws a line, saying she will be free to work and fight when she wants to.`,
      },
    ],
    weapon_url: '/characters/CINDY/weapon.png',
    skillAbility: [
      {
        skillName: 'one',
        commandSkill: 'weapon skill',
        url: '/characters/MICHELLE/skill_one.png',
      },
      {
        skillName: 'two',
        commandSkill: 'E skill',
        url: '/characters/MICHELLE/skill_two.png',
      },
      {
        skillName: 'three',
        commandSkill: 'shift skill',
        url: '/characters/MICHELLE/skill_three.png',
      },
    ],
  },
  {
    id: 3,
    ment: `"I'm just fighting to save”`,
    name: 'ALISHA',
    job: 'Nurse',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
    character_select_url: '/characters/ALISHA.png',
    character_example_url: '/guide/character/ALISHA.png',
    character_history: [
      {
        history: '',
      },
      {
        history: '',
      },
      {
        history: '',
      },
    ],
    weapon_url: '/characters/ALISHA/weapon.png',
    ambition: `Alicia, a doctor who inherited the genius of a genius doctor.She learns from her father's sudden disappearance and his research that there is a conspiracy.She became a military doctor for the special forces.He participates in the middle of chaos as a doctor and daughter to reveal all the secrets.`,
    skillAbility: [
      {
        skillName: 'RAIL GUN \n',
        commandSkill: 'weapon skill',
        url: '/characters/ALISHA/skill_one.png',
      },
      {
        skillName: 'HILL CAPSULE \n',
        commandSkill: 'E skill',
        url: '/characters/ALISHA/skill_two.png',
      },
      {
        skillName: 'Hook \n',
        commandSkill: 'shift skill',
        url: '/characters/ALISHA/skill_three.png',
      },
    ],
  },
  {
    id: 4,
    ment: `"Now my designs \n   are used to destroy the world."`,
    name: 'GRADY',
    job: 'Engineer',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
    character_select_url: '/characters/GRADY/GRADY.png',
    character_example_url: '/guide/character/GRADY.png',
    character_history: [
      {
        history: `A boy who looks up at the sky in rapture all day to see the Dyson Spear scientists create. He was Grady. Grady has been fascinated by machines operated by iron and unknown principles in the sky since the time Dyson Spear was built and assembled. From one point on, he was constantly making things, irresistibly inspired by Dyson Spear.`,
      },
      {
        history: `After studying at one of mankind's leading universities, graduate schools, and research courses, he became a doctor of public and chemistry at a very early age at the age of 25, and joined the Dyson Spear Project. I was so excited and spent every day working hard on the production of Spear. He realizes that the gravitational device is defective. However, in order to solve the abnormality of the gravity device, the Dyson Spear will be dismantled again, and the production progress will drop to less than half. FAITH's command and control department, which is in charge of producing Dyson Spear, only contradicting his opinion to develop a new device to solve the problem of gravity devices. They couldn't give up the huge budget and popular support from the Dyson Spear production. Eventually, Grady is imprisoned for attempting to inform the public.`,
      },
      {
        history: `How long has it been? Grady, while being locked up in Dyson Spear's special prison with other prisoners, is consumed by the darkness of the power-off prison, feeling an unknown roar and abnormal shaking throughout Dyson Spear. When he saw the light again, he was going down to the ground. What he witnessed there was the aftermath of the disastrous sinkhole. He is taken to a mining site with other prisoners and mobilized for gem mining and combining Halo and Gem.`,
      },
      {
        history: `There, he gains engineering superpowers along with superhuman powers as a side effect of combination work. After that, they escape by combining bombs and gems from the mining site, and hide in urban debris.With his escape, the combination of Jem and bombs is known, and the pandemic of bomb-type weapons begins, and "X" finds him after the rumor. Somehow X knew all FAITH's faults about the sinkhole and came to see Grady. Fascinated by X's belief in the collapse of FAITH and the liberation of the people, he follows X and joins CREED as an engineer and combatant.`,
      },
    ],
    weapon_url: '/characters/GRADY/weapon.png',
    ambition: `Grady, who warned of the dangers of Dyson Spear, is put in jail and becomes a prisoner of the mine. Grady, who escaped by\nbuilding a bomb with his genius ability, joins CREED and heads to the battlefield to change the world.`,
    skillAbility: [
      {
        skillName: 'powerful shotgun',
        commandSkill: 'weapon skill',
        url: '/characters/GRADY/skill_one.png',
      },
      {
        skillName: 'Acceleration gate',
        commandSkill: 'E skill',
        url: '/characters/GRADY/skill_two.png',
      },
      {
        skillName: 'Hook \n ',
        commandSkill: 'shift skill',
        url: '/characters/GRADY/skill_three.png',
      },
    ],
  },
  {
    id: 5,
    ment: `“All life is precious"`,
    name: 'KOONSMAN',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
    character_select_url: '/characters/KOONSMAN.png',
    character_example_url: '/guide/character/KOONSMAN.png',
    character_history: [
      {
        history:
          'A boy who looks up at the sky in rapture all day to see the Dyson Spear scientists create. He was Grady. Grady has been fascinated by machines operated by iron and unknown principles in the sky since the time Dyson Spear was built and assembled. From one point on, he was constantly making things, irresistibly inspired by Dyson Spear.',
      },
      {
        history: `After studying at one of mankind's leading universities, graduate schools, and research courses, he became a doctor of public and chemistry at a very early age at the age of 25, and joined the Dyson Spear Project. I was so excited and spent every day working hard on the production of Spear. He realizes that the gravitational device is defective. However, in order to solve the abnormality of the gravity device, the Dyson Spear will be dismantled again, and the production progress will drop to less than half. FAITH's command and control department, which is in charge of producing Dyson Spear, only contradicting his opinion to develop a new device to solve the problem of gravity devices. They couldn't give up the huge budget and popular support from the Dyson Spear production. Eventually, Grady is imprisoned for attempting to inform the public.`,
      },
      {
        history: `How long has it been? Grady, while being locked up in Dyson Spear's special prison with other prisoners, is consumed by the darkness of the power-off prison, feeling an unknown roar and abnormal shaking throughout Dyson Spear. When he saw the light again, he was going down to the ground. What he witnessed there was the aftermath of the disastrous sinkhole. He is taken to a mining site with other prisoners and mobilized for gem mining and combining Halo and Gem.`,
      },
      {
        history: `There, he gains engineering superpowers along with superhuman powers as a side effect of combination work. After that, they escape by combining bombs and gems from the mining site, and hide in urban debris.With his escape, the combination of Jem and bombs is known, and the pandemic of bomb-type weapons begins, and "X" finds him after the rumor. Somehow X knew all FAITH's faults about the sinkhole and came to see Grady. Fascinated by X's belief in the collapse of FAITH and the liberation of the people, he follows X and joins CREED as an engineer and combatant.`,
      },
    ],
    weapon_url: '/characters/KOONSMAN/weapon.png',
    ambition: `Idol Cindy! A job called an idol that was no longer needed in the Apocalypse era after the sinkhole incident, but she still claims to be an idol. Having gained psychotic and abnormal physical abilities through her work at the mining site,Once again, I'll use this power to make my debut as an idol on the battlefield idol!`,
    skillAbility: [
      {
        skillName: 'one',
        commandSkill: 'weapon skill',
        url: '/characters/MICHELLE/skill_one.png',
      },
      {
        skillName: 'two',
        commandSkill: 'E skill',
        url: '/characters/MICHELLE/skill_two.png',
      },
      {
        skillName: 'three',
        commandSkill: 'shift skill',
        url: '/characters/MICHELLE/skill_three.png',
      },
    ],
  },
  {
    id: 6,
    ment: `"Now my designs \n   are used to destroy the world."`,
    name: 'MICHELLE',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
    character_select_url: '/characters/MICHELLE.png',
    character_example_url: '/guide/character/MICHELLE.png',
    character_history: [
      {
        history: `He is a specialist in bomb disposal as a member of the Special Task Force on Counter Terrorism under the FAITH. There were not many people around because he was a principled and inflexible principleist because he had lived as a soldier all his life since he grew up. Moreover, her face, which is always covered, did not even allow others to distinguish her gender.
        `,
      },
      {
        history: `The sinkhole crisis. The global catastrophe has shaken her situation greatly, too. The regular army became more focused on relief activities rather than its usual duties, and she was also sent to the scene to identify the greatly changed terrain and the resulting hazards.`,
      },
      {
        history: `The U.S. FAITH decides to send Michelle from the bomb squad down to the site's steward.Since then, every day has been a series of boredom. Prisoners who have to work the same every day and themselves who have to watch it the same. There were only accidents caused by bombs at times, but they only caused them according to the rules. One day news of a bomb accident came, but the report was strange. It's not an accident. It's an accident.When she arrived at the scene, it was more than an ordinary bomb exploded. A trace as if something had been attacked with a huge weapon, and through the Work and Human Resources Department, we find out that the suspect in the case was a prisoner named Grady. That's also a special prisoner in Dyson Spear Special Prison. She was not particularly interested in the scene, but after that, as she paid attention to the scene, she began to see various things that were not visible.drugs in vogue among them The existence of a veiled organization that is rumored to be. With a little attention, she began to enjoy life under the sinkhole. The FAITH intelligence agency's directive, which just came down at that time. [The deterrence of the terrorist organization CREED and the eradication of drug distribution]And Alicia volunteered to be the doctor at the mine shelter. Michelle is starting to find the whole situation interesting and exciting.`,
      },
    ],
    weapon_url: '/characters/MICHELLE/weapon.png',
    ambition: `She is FAITH's bomb disposal specialist. While spending boring and boring days, she finds new fun by carrying out special missions at the sinkhole.`,
    skillAbility: [
      {
        skillName: 'MISSILE \n ',
        commandSkill: 'weapon skill',
        url: '/characters/MICHELLE/skill_one.png',
      },
      {
        skillName: 'SHIELD \n ',

        commandSkill: 'E skill',

        url: '/characters/MICHELLE/skill_two.png',
      },
      {
        skillName: 'HOOK \n ',
        commandSkill: 'shift skill',
        url: '/characters/MICHELLE/skill_three.png',
      },
    ],
  },
  {
    id: 7,
    ment: `“All life is precious"`,
    name: 'COMMING SOON',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
    character_select_url: '/characters/MICHELLE.png',
    character_example_url: '/guide/character/MICHELLE.png',
    character_history: [
      {
        history: '',
      },
      {
        history: '',
      },
      {
        history: '',
      },
    ],
    weapon_url: '/characters/MICHELLE/weapon.png',
    ambition: `Idol Cindy! A job called an idol that was no longer needed in the Apocalypse era after the sinkhole incident, but she still claims to be an idol. Having gained psychotic and abnormal physical abilities through her work at the mining site,Once again, I'll use this power to make my debut as an idol on the battlefield idol!`,
    skillAbility: [
      {
        skillName: 'one',
        commandSkill: 'weapon skill',
        url: '/characters/MICHELLE/skill_one.png',
      },
      {
        skillName: 'two',
        commandSkill: 'E skill',
        url: '/characters/MICHELLE/skill_two.png',
      },
      {
        skillName: 'three',
        commandSkill: 'shift skill',
        url: '/characters/MICHELLE/skill_three.png',
      },
    ],
  },
  {
    id: 8,
    ment: `“All life is precious"`,
    name: 'COMMING SOON',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
    character_select_url: '/characters/MICHELLE.png',
    character_example_url: '/guide/character/MICHELLE.png',
    character_history: [
      {
        history: '',
      },
      {
        history: '',
      },
      {
        history: '',
      },
    ],
    weapon_url: '/characters/MICHELLE/weapon.png',
    ambition: `Idol Cindy! A job called an idol that was no longer needed in the Apocalypse era after the sinkhole incident, but she still claims to be an idol. Having gained psychotic and abnormal physical abilities through her work at the mining site,Once again, I'll use this power to make my debut as an idol on the battlefield idol!`,
    skillAbility: [
      {
        skillName: 'one',
        commandSkill: 'weapon skill',
        url: '/characters/MICHELLE/skill_one.png',
      },
      {
        skillName: 'two',
        commandSkill: 'E skill',
        url: '/characters/MICHELLE/skill_two.png',
      },
      {
        skillName: 'three',
        commandSkill: 'shift skill',
        url: '/characters/MICHELLE/skill_three.png',
      },
    ],
  },
]
