export const Request_CharacterInfo = [
  {
    id: 1,
    name: 'Olie',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
  },
  {
    id: 2,
    name: 'Idol',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
  },
  {
    id: 3,
    name: 'Nurse',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
  },
  {
    id: 4,
    name: 'Health',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
  },
  {
    id: 5,
    name: 'Alien',
    job: 'delivery',
    charactermessage: `In accordance with my father's will, "All life is precious," I decided to be the fairest nurse.`,
    realName: 'realName',
    age: 'age',
    homeWorld: 'homeworld',
    tacticalAbliity: 'TacticalAbliity',
    passiveAbility: 'Passive Ability',
    ultimateAbility: 'Ultimate Ability',
  },
]
