import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useEffect, useRef, useState } from 'react'
import styled from '@emotion/styled'
import { useRouter } from 'next/router'
import { Container, css } from '@mui/material'
import FatalZoneInfo from 'src/components/FatalZoneInfo'
import FatalZoneMap from 'src/components/FatalZoneMap'
import FatalCharacters from 'src/components/FatalCharacters'
import FatalInsert from 'src/components/FatalInsert'
import FatalHalo from 'src/components/FatalHalo'
import web_logo from 'src/assets/image/MainPageLogo.png'
import mobile_logo from 'src/assets/image/mobile_center_img.png'
import Button from 'src/components/commons/Button'
import arrow from 'src/assets/icon/arrow.png'
const inter = Inter({ subsets: ['latin'] })

const Wrapper = styled('div')({
  width: '100%',
  height: '100vh',
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#959595',
  overflowX: 'hidden',
})

const MainCenter = styled('div')(
  css`
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    color: #fff;
    font-weight: 400;
    p {
      font-size: 20px;
      padding-top: 13px;
    }
  `
)

const MainText = styled('div')(
  css`
    width: 100%;
    font-weight: 500;
    font-size: 16px;
    color: #fff;
    text-align: center;
    padding-bottom: 5.5rem;
    font-family: 'Inter';
    font-style: normal;

    @media (max-width: 480px) {
      width: 80%;
    }
  `
)

const MainLogoText = styled('div')(
  css`
    font-family: 'KoreanRKTR';
    font-style: normal;
    font-weight: 400;
    font-size: 2.6rem;
    text-align: center;
    color: #ffffff;
    padding-top: 2rem;
    @media (max-width: 480px) {
      font-size: 1.2rem;
    }
  `
)

const MainContent = styled('div')(
  css`
    position: absolute;
    display: flex;
    flex-direction: column;
    align-items: center;
    bottom: 3rem;
  `
)

const LineProvider = styled('div')(
  css`
    width: 100%;
    height: 2.5rem;
    background: #d3d3d3;
  `
)

const FatalZoneStage = styled('div')(
  css`
    width: 100%;
    height: 168px;
    background: #0c0c0c;
    font-family: 'KoreanRKTR';
    font-style: normal;
    font-weight: 400;
    font-size: 3.5rem;
    text-align: center;
    color: #ffffff;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    @media (max-width: 1350px) {
      font-size: 2rem;
    }
    @media (max-width: 480px) {
      font-size: 20px;
    }
    p {
      font-family: 'Bebas';
      font-style: normal;
      font-weight: 400;
      font-size: 1rem;
      text-align: center;
      letter-spacing: 0.675em;

      color: #ffffff;
      @media (max-width: 1350px) {
        font-size: 0.8rem;
      }
      @media (max-width: 480px) {
        font-size: 7px;
      }
    }
  `
)

const TopButton = styled('button')(
  css`
    width: 45px;
    height: 45px;
    background-color: #000;
    position: fixed;
    right: 30px;
    bottom: 40px;
    z-index: 1;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
  `
)

export default function Home() {
  const router = useRouter()
  // 이미지 모바일
  const [isMobile, setIsMobile] = useState<boolean>(false)

  //화면 resize
  const [mobileResize, setMobileResize] = useState<number>(0)

  const handleResize = () => {
    setMobileResize(window.innerWidth)
  }

  useEffect(() => {
    window.addEventListener('resize', handleResize)

    const time = setTimeout(() => {
      setMobileResize(window.innerWidth)
    }, 0.0000000000000000001)

    return () => {
      window.removeEventListener('resize', handleResize)
      clearTimeout(time)
    }
  }, [])

  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth <= 480) {
        setIsMobile(true)
      } else {
        setIsMobile(false)
      }
    }

    handleResize()
    window.addEventListener('resize', handleResize)

    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [])

  console.log(mobileResize)

  console.log(isMobile)

  return (
    <>
      <Head>
        <title>FATAL BOMB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Wrapper>
          <MainCenter>
            {mobileResize >= 480 ? (
              <MainText>
                <p>5-5 Team-Based Action Tactical Game</p>
              </MainText>
            ) : null}
            <Image
              src={mobileResize >= 480 ? web_logo : mobile_logo}
              width={mobileResize >= 480 ? 687 : 325}
              alt="logo"
            />
            <MainLogoText>THROW IT INTO THE WOLRD!</MainLogoText>
          </MainCenter>
          <MainContent>
            {mobileResize <= 480 ? (
              <MainText>
                <p>5-5 Team-Based Action Tactical Game</p>
              </MainText>
            ) : null}
            {/* <MainText>
              <p>5-5 Team-Based Action Tactical Game</p>
            </MainText> */}
            <div>
              <Button
                width="201px"
                height="54px"
                backgroundColor="#313131"
                type="button"
                color="#fff"
                fontSize="18px"
                fontFamily="Inter"
                fontStyle="normal"
                border="none"
                style={{
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center',
                  fontWeight: '700',
                }}
              >
                START FREE
              </Button>
            </div>
          </MainContent>
        </Wrapper>
        <LineProvider />
        <FatalZoneInfo />
        <FatalZoneStage>
          Welcome Stage Fatal Zone
          <p>NEVER - ENDING BATTLE IN FATAL ZONE</p>
        </FatalZoneStage>
        <FatalHalo />
        <FatalZoneMap />
        <FatalCharacters />
        <FatalInsert />
        <TopButton>
          <Image src={arrow} alt="go to Top" />
        </TopButton>
      </main>
    </>
  )
}
