import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useEffect, useRef, useState } from 'react'
import styled from '@emotion/styled'
import { useRouter } from 'next/router'
import { Container } from '@mui/material'
const inter = Inter({ subsets: ['latin'] })

const Warpper = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  color: black;
`

const BtContainer = styled.div`
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 3rem;
`

const Button = styled.button`
  width: 100px;
  height: 50px;
  background-color: red;
  color: #000;
  border: 1px solid black;
`

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="xl">
          <Warpper>
            <h2 style={{ padding: '5rem' }}>어서오세요 ???님</h2>
            <BtContainer>
              <Button onClick={() => router.push('/signup')}>가입</Button>
              <Button onClick={() => router.push('/login')}>로그인</Button>
              <Button onClick={() => router.push('/logout')}>로그아웃</Button>
            </BtContainer>
          </Warpper>
        </Container>
      </main>
    </>
  )
}
