import Head from 'next/head'
import React from 'react'

interface CustomHeadProps {
  title: string
  description: string
  ogImage: string
  ogUrl?: string
}

const CustomHead: React.FC<CustomHeadProps> = ({
  title,
  description,
  ogImage,
  ogUrl,
}) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description} />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:image" content={ogImage} />
      <meta property="og:description" content="세상을 향해 지배하자" />
      {ogUrl && <meta property="og:url" content={ogUrl} />}
      <link rel="icon" href="/favicon.ico" />
      {/* <title>FATAL BOMB</title> */}
      {/* <meta name="description" content="Generated by create next app" />
      <meta name="view-transition" content="same-origin" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property="og:title" content="FATAL BOMB" />
      <meta property="og:description" content="세상을 향해 지배하자" />
      <meta property="og:image" content="/main.PNG" /> */}
      {/* <meta property="og:url" content="https://my-page.com" /> 추후 주소 수정  */}
      {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>
  )
}

export default CustomHead
